fix compile error.
ERROR: /frameworks/opt/telephony/tests/telephonytests/src/com/android/internal/telephony/mocks/ConnectivityServiceMock.java:146:
The type ConnectivityServiceMock must implement the inherited abstract method IConnectivityManager.getTetherConnectedSta()

This was introduced by commit:https://review.cyanogenmod.org/#/c/169526/,
which added a new method that should be implemented.

Change-Id: I065bbdd6a3fb8df8d888affe1789bd3b94be49e9
Signed-off-by: Hriday Sharma <hridaysharma42@gmail.com>